name: flip_drawer
description: An easy way to use drawer in Flutter with cool flipping animation.
version: 1.0.2
author: Salman S
homepage: https://github.com/salkuadrat/flip_drawer
repository: https://github.com/salkuadrat/flip_drawer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  curved_animation_controller: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter